[package]
name = "propagator_scheduler_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "propagator_scheduler_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.24.0"
ordered-float = "5.0.0"
